In [5]:
import pandas as pd
import numpy as np

dates=pd.date_range(start='2024-01-01', end='2024-03-31')
channels=['Paid Search', 'Paid Social', 'Affiliates', 'Display', 'Retail QR', 'App Store Ads']

data=[]

base_spend= {'Paid Search': 50000, 'Paid Social': 30000, 'Affiliates': 15000, 'Display': 10000, 'Retail QR': 5000, 'App Store Ads': 8000}
for d in dates:
    for c in channels:
        spend=base_spend[c] * np.random.uniform(0.7,1.3)
        if d.weekday()>=5: spend*=0.8
        data.append([d,c,round(spend,2)])

df_spend=pd.DataFrame(data, columns=['date', 'channel', 'spend'])
df_spend.to_csv('C:\\Users\\freak\\.cache\\kagglehub\\datasets\\Syntheticdatacsvs\\channel_spend.csv', index=False)
df_spend.head()

        date      channel     spend
0 2024-01-01  Paid Search  60679.26
1 2024-01-01  Paid Social  25606.82
2 2024-01-01   Affiliates  10701.21
3 2024-01-01      Display  10155.13
4 2024-01-01    Retail QR   3708.08

In [6]:
ctr_map={'Paid Search': (0.03,0.05), 'Paid Social': (0.01,0.02), 'Affiliates': (0.04, 0.06), 'Display': (0.005,0.01), 'Retail QR': (0.10, 0.15), 'App Store Ads': (0.02,0.03)}
                                                                                                                                    
data=[]

for d in dates:
    for c in channels:
        impressions= np.random.randint(5000, 50000)
        ctr_low, ctr_high=ctr_map[c]
        ctr=np.random.uniform(ctr_low, ctr_high)
        clicks=int(impressions*ctr)
        data.append([d,c,impressions,clicks])

df_ic=pd.DataFrame(data, columns=['date', 'channel', 'impressions', 'clicks'])
df_ic.to_csv('C:\\Users\\freak\\.cache\\kagglehub\\datasets\\Syntheticdatacsvs\\impressions_clicks.csv', index=False)                                 

df_ic.head()

        date      channel  impressions  clicks
0 2024-01-01  Paid Search         6060     231
1 2024-01-01  Paid Social        18401     261
2 2024-01-01   Affiliates        33981    1416
3 2024-01-01      Display        11178      96
4 2024-01-01    Retail QR         6574     730

In [9]:
n=50000

df_funnel=pd.DataFrame({'customer_id': range(1,n+1),})
df_funnel['app_start']=np.random.binomial(1,0.3,n)
df_funnel['app_complete']=df_funnel['app_start']*np.random.binomial(1,0.7,n)
df_funnel['approved']=df_funnel['app_complete']*np.random.binomial(1,0.4,n)
df_funnel['activated']=df_funnel['approved']*np.random.binomial(1,0.8,n)

df_funnel.to_csv('C:\\Users\\freak\\.cache\\kagglehub\\datasets\\Syntheticdatacsvs\\app_funnel.csv', index=False)

In [12]:
stores = range(1, 51)
dates = pd.date_range('2024-01-01', '2024-03-31')

data = []

for s in stores:
    for d in dates:
        scans = np.random.randint(5, 50)
        if d.weekday() >= 5:
            scans = int(scans * 1.5)
        approvals = int(scans * np.random.uniform(0.2, 0.4))
        data.append([s, d, scans, approvals])

df_qr = pd.DataFrame(data, columns=['store_id', 'date', 'scans', 'approvals'])
df_qr.to_csv('C:\\Users\\freak\\.cache\\kagglehub\\datasets\\Syntheticdatacsvs\\retail_qr_scans.csv', index=False)
df_qr.head()

   store_id       date  scans  approvals
0         1 2024-01-01     44         15
1         1 2024-01-02     48          9
2         1 2024-01-03     38         13
3         1 2024-01-04     27          6
4         1 2024-01-05     10          3